// import mongoose
const mongoose = require("mongoose");

// route Handler
const commentSchema = new mongoose.Schema({
  post: {
    type: mongoose.Schema.Types.ObjectId,
    // This specifies that the post field should store an ObjectId.
    // An ObjectId is a unique identifier used by MongoDB to identify documents within a collection. It's a 12-byte value that is automatically generated by MongoDB when a document is created.
    // By using mongoose.Schema.Types.ObjectId, you're saying that this field will hold an ID that corresponds to another document.
    ref: "Post", //this is refrence to the Post Model created in the model folder
    // The ref property tells Mongoose which Model the ObjectId refers to.
  },
  user: {
    type: String,
    required: true,
  },
  body: {
    type: String,
    required: true,
  },
});

// export
module.exports = mongoose.model("Comments", commentSchema);
